GET http://localhost:5032/getProduct

###
GET http://localhost:5032/

###
POST http://localhost:5032/api/v1/categories
Content-Type: application/json

{
    "name": "Hi Look",
    "description" : "Book Data Descriptions and Forwarded:  Descriptions."
}

###
GET  http://localhost:5032/api/v1/categories

###
GET  http://localhost:5032/api/v1/categories/a338539f-1459-4ef6-9104-1e9787ae9bd1


###
DELETE   http://localhost:5032/api/v1/categories/da3e4072-0b6d-451b-b113-ca60bf010d01e

###
DELETE   http://localhost:5032/api/v1/categories/



###
GET http://localhost:5032/api/v2/categories?searchValue=Clothing


###
PUT http://localhost:5032/api/v1/categories/665839ed-18f2-4b8d-937d-020b7d1a5d93
Content-Type: application/json

{
    "name": "update",
    "description": "update hello sir this is very top"
}
