GET http://localhost:5032/getProduct

###
GET http://localhost:5032/

###
POST http://localhost:5032/api/v1/categories
Content-Type: application/json

{
    "name": "Laptop",
    "description" : "Cloth Data Descriptions and Forwarded:  Descriptions."
}

###
GET  http://localhost:5032/api/v1/categories

###
GET  http://localhost:5032/api/v1/categories/5bb8fe5c-6b8b-401b-9785-1cd9fcb05274


###
DELETE   http://localhost:5032/api/v1/categories/9b7ab99e-c8cb-4138-83ec-48068d00fdc8

###
DELETE   http://localhost:5032/api/v1/categories/



###
GET http://localhost:5032/api/v2/categories?searchValue=Clothing


###
PUT http://localhost:5032/api/v1/categories/5bb8fe5c-6b8b-401b-9785-1cd9fcb05274
Content-Type: application/json

{
    "name": "update",
    "description": "update hello sir this is very top"
}
