@TEcommerceWebApi_HostAddress = http://localhost:5131

GET {{TEcommerceWebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5131/

###
GET http://localhost:5131/api/v2/categories

###
POST http://localhost:5131/api/v2/categories
Content-Type: application/json

{
    "name": "Cricket",
    "description": "Cricket is not the more acceptable game in many country."
}

###
GET http://localhost:5131/api/v2/categories/0daee4f0-8d2f-4e1a-b030-d1063c02ef67


###
PUT http://localhost:5131/api/v2/categories/813b541e-c793-4847-a9e5-8b638f5bb537
Content-Type: application/json

{
    "name": "Basketball",
    "description": "Cricket is not the more acceptable game in many country."
}

###
DELETE  http://localhost:5131/api/v2/categories/813b541e-c793-4847-a9e5-8b638f5bb537