@TEcommerceWebApi_HostAddress = http://localhost:5131

GET {{TEcommerceWebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET http://localhost:5131/

###
GET http://localhost:5131/api/v2/categories

###
POST http://localhost:5131/api/v2/categories
Content-Type: application/json

{
    "name": "Cricket",
    "description": "Cricket is not the more acceptable game in many country."
}

###
GET http://localhost:5131/api/v2/categories/0daee4f0-8d2f-4e1a-b030-d1063c02ef67


###
PUT http://localhost:5131/api/v2/categories/7d2112e4-1b7b-48f0-bd18-52e1753a1300
Content-Type: application/json

{
    "name": "Basketball",
    "description": "Cricket is not the more acceptable game in many country."
}

###
DELETE  http://localhost:5131/api/v2/categories/7d2112e4-1b7b-48f0-bd18-52e1753a1300


###
POST http://localhost:5131/api/v2/products
Content-Type: application/json

{
    "name": "Stamp",
    "price": 150.0,
    "categoryid": "68af6bda-6ba9-45b6-9575-cba753ef117a"
}

###
GET  http://localhost:5131/api/v2/products

###
POST http://localhost:5131/api/v2/products
Content-Type: application/json

{
    "name": "Tennis Wristband",
    "price": 350.0,
    "categoryid": "16e09039-3ef3-415e-852c-eaa628ac20a6"
}